#!/usr/bin/env bash

declare -A aliases
declare -A helptext
declare -r c_reset=$(tput sgr0)
declare -r c_red=$(tput setaf 1)
declare -r c_green=$(tput setaf 2)
declare -r c_yellow=$(tput setaf 3)
declare -r c_grey=$(tput setaf 8)

err() {
  printf "${c_red}%s${c_reset}\n" "$*" >&2
}

die() {
  if (( $# > 0 )); then
    err "$@"
  fi
  exit 1
}

has() {
  local v c
  if [[ $1 = '-v' ]]; then
    v=1
    shift
  fi
  for c; do c="${c%% *}"
    if ! command -v "$c" &> /dev/null; then
      (( v > 0 )) && err "$c not found"
      return 1
    fi
  done
}

aliases[-h]=help
aliases[--help]=help
helptext[help]='show this help'
subcmd_help() {
  local formattedhelptext

  formattedhelptext=$(for c in "${subcmds_avail[@]}"; do
    printf "  %s\n    %s\n" "$c" "${helptext[$c]}"
  done)
  LESS=-FEXR less <<-HELP
$0 <COMMAND>

${formattedhelptext}
HELP
}

fzf() {
  local prompt
  if [[ $1 == --prompt=* ]]; then
    prompt="${1##*=}>"
    shift
  fi
  branch=$(git status 2> /dev/null | sed 's/On branch />/;q')
  opts=( --prompt="fzgit${branch}>${prompt} " )
  [[ -v FZGIT_OPTIONS ]] && opts=( $FZGIT_OPTIONS )
  command fzf "${opts[@]}" \
    --inline-info \
    --ansi \
    --no-clear \
    "$@"
}

declare -A git_cmds_descriptions=( # {{{
  ['add']='Add file contents to the index'
  ['am']='Apply a series of patches from a mailbox'
  ['annotate']='Annotate file lines with commit information'
  ['apply']='Apply a patch to files and/or to the index'
  ['archive']='Create an archive of files from a named tree'
  ['bisect']='Find by binary search the change that introduced a bug'
  ['blame']='Show what revision and author last modified each line of a'
  ['branch']='List, create, or delete branches'
  ['bundle']='Move objects and refs by archive'
  ['cat-file']='Provide content or type and size information for'
  ['check-attr']='Display gitattributes information'
  ['check-ignore']='Debug gitignore / exclude files'
  ['check-mailmap']='Show canonical names and email addresses of'
  ['check-ref-format']='Ensures that a reference name is well formed'
  ['checkout']='Checkout a branch or paths to the working tree'
  ['checkout-index']='Copy files from the index to the working tree'
  ['cherry']='Find commits yet to be applied to upstream'
  ['cherry-pick']='Apply the changes introduced by some existing commits'
  ['citool']='Graphical alternative to git-commit'
  ['clean']='Remove untracked files from the working tree'
  ['clone']='Clone a repository into a new directory'
  ['column']='Display data in columns'
  ['commit']='Record changes to the repository'
  ['commit-tree']='Create a new commit object'
  ['config']='Get and set repository or global options'
  ['count-objects']='Count unpacked number of objects and their disk'
  ['credential']='Retrieve and store user credentials'
  ['daemon']='A really simple server for Git repositories'
  ['describe']='Show the most recent tag that is reachable from a commit'
  ['diff']='Show changes between commits, commit and working tree, etc'
  ['diff-files']='Compares files in the working tree and the index'
  ['diff-index']='Compare a tree to the working tree or index'
  ['diff-tree']='Compares the content and mode of blobs found via two'
  ['difftool']='Show changes using common diff tools'
  ['fast-export']='Git data exporter'
  ['fast-import']='Backend for fast Git data importers'
  ['fetch']='Download objects and refs from another repository'
  ['fetch-pack']='Receive missing objects from another repository'
  ['filter-branch']='Rewrite branches'
  ['fmt-merge-msg']='Produce a merge commit message'
  ['for-each-ref']='Output information on each ref'
  ['format-patch']='Prepare patches for e-mail submission'
  ['fsck']='Verifies the connectivity and validity of the objects in the'
  ['fsck-objects']='Verifies the connectivity and validity of the'
  ['gc']='Cleanup unnecessary files and optimize the local repository'
  ['get-tar-commit-id']='Extract commit ID from an archive created using'
  ['grep']='Print lines matching a pattern'
  ['gui']='A portable graphical interface to Git'
  ['hash-object']='Compute object ID and optionally creates a blob from'
  ['help']='Display help information about Git'
  ['http-backend']='Server side implementation of Git over HTTP'
  ['http-fetch']='Download from a remote Git repository via HTTP'
  ['http-push']='Push objects over HTTP/DAV to another repository'
  ['imap-send']='Send a collection of patches from stdin to an IMAP'
  ['index-pack']='Build pack index file for an existing packed archive'
  ['init']='Create an empty Git repository or reinitialize an existing'
  ['init-db']='Creates an empty Git repository'
  ['instaweb']='Instantly browse your working repository in gitweb'
  ['log']='Show commit logs'
  ['ls-files']='Show information about files in the index and the'
  ['ls-remote']='List references in a remote repository'
  ['ls-tree']='List the contents of a tree object'
  ['mailinfo']='Extracts patch and authorship from a single e-mail'
  ['mailsplit']='Simple UNIX mbox splitter program'
  ['merge']='Join two or more development histories together'
  ['merge-base']='Find as good common ancestors as possible for a merge'
  ['merge-file']='Run a three-way file merge'
  ['merge-index']='Run a merge for files needing merging'
  ['merge-one-file']='The standard helper program to use with'
  ['merge-tree']='Show three-way merge without touching index'
  ['mergetool']='Run merge conflict resolution tools to resolve merge'
  ['mktag']='Creates a tag object'
  ['mktree']='Build a tree-object from ls-tree formatted text'
  ['mv']='Move or rename a file, a directory, or a symlink'
  ['notes']='Add or inspect object notes'
  ['pack-objects']='Create a packed archive of objects'
  ['pack-redundant']='Find redundant pack files'
  ['pack-refs']='Pack heads and tags for efficient repository access'
  ['patch-id']='Compute unique ID for a patch'
  ['prune']='Prune all unreachable objects from the object database'
  ['prune-packed']='Remove extra objects that are already in pack files'
  ['pull']='Fetch from and integrate with another repository or a local'
  ['push']='Update remote refs along with associated objects'
  ['quiltimport']='Applies a quilt patchset onto the current branch'
  ['read-tree']='Reads tree information into the index'
  ['rebase']='Forward-port local commits to the updated upstream head'
  ['receive-pack']='Receive what is pushed into the repository'
  ['reflog']='Manage reflog information'
  ['relink']='Hardlink common objects in local repositories'
  ['remote']='Manage set of tracked repositories'
  ['remote-ext']='Bridge smart transport to external command.'
  ['remote-fd']='Reflect smart transport stream back to caller'
  ['repack']='Pack unpacked objects in a repository'
  ['replace']='Create, list, delete refs to replace objects'
  ['request-pull']='Generates a summary of pending changes'
  ['rerere']='Reuse recorded resolution of conflicted merges'
  ['reset']='Reset current HEAD to the specified state'
  ['rev-list']='Lists commit objects in reverse chronological order'
  ['rev-parse']='Pick out and massage parameters'
  ['revert']='Revert some existing commits'
  ['rm']='Remove files from the working tree and from the index'
  ['send-pack']='Push objects over Git protocol to another repository'
  ['sh-i18n--envsubst']="Git's own envsubst(1) for i18n fallbacks"
  ['shell']='Restricted login shell for Git-only SSH access'
  ['shortlog']="Summarize 'git log' output"
  ['show']='Show various types of objects'
  ['show-branch']='Show branches and their commits'
  ['show-index']='Show packed archive index'
  ['show-ref']='List references in a local repository'
  ['stage']='Add file contents to the staging area'
  ['stash']='Stash the changes in a dirty working directory away'
  ['status']='Show the working tree status'
  ['stripspace']='Remove unnecessary whitespace'
  ['submodule']='Initialize, update or inspect submodules'
  ['subtree']='Merge subtrees together and split repository into'
  ['symbolic-ref']='Read, modify and delete symbolic refs'
  ['tag']='Create, list, delete or verify a tag object signed with GPG'
  ['unpack-file']="Creates a temporary file with a blob's contents"
  ['unpack-objects']='Unpack objects from a packed archive'
  ['update-index']='Register file contents in the working tree to the'
  ['update-ref']='Update the object name stored in a ref safely'
  ['update-server-info']='Update auxiliary info file to help dumb'
  ['upload-archive']='Send archive back to git-archive'
  ['upload-pack']='Send objects packed back to git-fetch-pack'
  ['var']='Show a Git logical variable'
  ['verify-commit']='Check the GPG signature of commits'
  ['verify-pack']='Validate packed Git archive files'
  ['verify-tag']='Check the GPG signature of tags'
  ['web--browse']='Git helper script to launch a web browser'
  ['whatchanged']='Show logs with difference each commit introduces'
  ['write-tree']='Create a tree object from the current index'
)


subcmd_diff() {
  if (( $# > 0 )); then git diff "$@"; fi
  fzf \
    --bind='start:reload:git -c color.status=always status -su' \
    --nth=2.. \
    --preview='git diff --color=always {2..} | delta -w $FZF_PREVIEW_COLUMNS' \
    --bind='enter:execute:git diff --color=always {2..}' \
    --preview-window=70%
}

subcmd_add() {
  if (( $# > 0 )); then git add "$@"; return; fi
  local diff
  diff=$(git diff --color=always | perl -pwe 's/^(\e\[[0-9;]*m)*(?=diff)/\0/m' | fzf --read0)
  [[ -z $diff ]] && return
  git apply --check --cached <<< "$diff" &&
    git apply --cached <<< "$diff" &&
    git apply --stat <<< "$diff"
  subcmd_add
}

subcmd_status() {
  local preview='git diff --color=always {2..}'
  fzf \
    --nth=2.. \
    --bind='start:reload:git -c color.status=always status -s' \
    --preview="$preview" \
    --bind='enter:execute:git add -p {2..}'
}

subcmd_checkout() { # {{{
  local list response key branch header
  if (( $# > 0 )); then git checkout "$@"; return; fi
  {
    git branch --all --color -vv
    git tag
  } |
    fzf --prompt='checkout' \
    --header="$header" \
    --bind=enter:execute:"git checkout \$(perl -pe 's/^\*?\s*(remotes\/[^\/]*\/)?([^ ]+).*/\2/' <<< {})"

}

subcmd_stash() {
  if (( $# > 0 )); then git stash "$@"; return; fi
  local header='use ctrl-d to show a diff or ctrl-b to create a new branch'
  git stash list --pretty="%C(yellow)%h %>(14)%Cgreen%cr %C(blue)%gs" |
    fzf --prompt='stash' --no-sort --header="$header" \
    --bind='ctrl-d:execute: git diff {1} --color=always | less -R' \
    --bind='ctrl-b:execute(git stash branch "stash-{1}" {1})+abort' \
    --preview='git diff --color {1}'
}

has -v fzf perl git || die

mapfile -t subcmds_avail < <(compgen -A function | awk '/^subcmd_/ { sub(/^subcmd_/, "", $0); print }')

nocmd() {
  local cmd=$(for c in "${subcmds_avail[@]}"; do
    printf "$c\t${help}\t${git_cmds_descriptions[$c]}\n"
  done)
  local choice=$(<<< "$cmd" column -t -s $'\t' | fzf | awk '{print $1}')
  if [[ -z $choice ]]; then exit 1; fi
  subcmd_$choice
}

if (( $# < 1 )); then
  nocmd
  exit 1
elif has "subcmd_$1"; then
  subcmd="subcmd_$1"
  shift
  "$subcmd" "$@"
elif [[ -v aliases[$1] ]]; then
  subcmd=subcmd_${aliases[$1]}
  shift
  "$subcmd" "$@"
else
  exec git "$@"
fi
