#!/usr/bin/env bash

declare esc=$(printf '\033')
declare c_reset="${esc}[0m"
declare c_red="${esc}[31m"

usage() {
  more <<'HELP'
fzmp [OPTIONS]

  -A --all       search all songs in the library (or F1)
  -a --artist    search artist then filter by album (or F2)
  -p --playlist  search the current playlist (or F3)
  -h --help      print this help
HELP
}

isRunning() {
  pgrep "$1" &> /dev/null
}

err() {
  echo -e "${c_red}$1${c_reset}" >&2
}

die() {
  [[ -n "$1" ]] && err "$1"
  exit 1
}

has() {
  local verbose=false
  if [[ $1 == '-v' ]]; then
    verbose=true
    shift
  fi
  for c in "$@"; do c="${c%% *}"
    if ! command -v "$c" &> /dev/null; then
      [[ "$verbose" == true ]] && err "$c not found"
      return 1
    fi
  done
}

fzf() {
  command fzf -e --reverse --cycle +s --inline-info "$@"
}

filterAll() {
  local choice
  mapfile -t choice < <( mpc search -f '[[[%artist% / ][[(%date%) ]%album% / ][%track%] [%title%]]|%file%] \t%file%' filename '' |
    fzf --multi \
      --with-nth='..-2' \
      --delimiter='\t' \
      --expect='f2,f3' |
    cut -f2)
  (( "${#choice[@]}" > 0 )) || die
  if [[ "${choice[0]}" == '' ]]; then
    printf '%s\n' "${choice[@]:1}"
  elif [[ "${choice[0]}" == 'f2' ]]; then
    filterByArtist
  elif [[ "${choice[0]}" == 'f3' ]]; then
    filterByPlaylist
  fi
}

filterByArtist() {
  local choice
  mapfile -t choice < <(mpc list artist | sort -h | fzf --expect='f1,f3')
  (( "${#choice[@]}" > 0 )) || die
  if [[ "${choice[0]}" == '' ]]; then
    filterByAlbum "${choice[1]}"
  elif [[ "${choice[0]}" == 'f1' ]]; then
    filterAll
  elif [[ "${choice[0]}" == 'f3' ]]; then
    filterByPlaylist
  fi
}

filterByAlbum() {
  local album artist
  [[ -z "$1" ]] && die
  artist="$1"
  album=$(mpc search -f '[(%date%)]\t%album%' artist "${artist}" |
    sort -u |
    fzf --prompt="$artist > " |
    cut -f2 )
  if [[ -z "$album" ]]; then
    filterByArtist
    return 0
  fi
  filterBySong "$artist" "$album"
}

filterBySong() {
  local album artist choice
  [[ -z "$1" || -z "$2" ]] && die
  artist="$1"
  album="$2"
  choice=$(mpc search -f '[[[%track% - ][%title%]]|%file%] \t%file%' artist "${artist}" album "${album}" |
    fzf --prompt="$artist - $album > " \
      --multi \
      --with-nth='..-2' \
      --delimiter='\t' \
      --bind='Ctrl-A:select-all' |
    cut -f2)
  if [[ -z "$choice" ]]; then
    filterByAlbum "$artist"
    return 0
  fi
  echo "$choice"
}

filterByPlaylist() {
  local choice
  mapfile -t choice < <(mpc playlist -f '[%artist% / ][[(%date%) ]%album% / ][%title%|%file%]' |
    nl |
    fzf --prompt='playlist> ' \
      --with-nth='2..' \
      --expect='f1,f2' \
      --delimiter='\t' |
    cut -f1)
  (( "${#choice[@]}" > 0 )) || die
  if [[ "${choice[0]}" == '' ]]; then
    mpc -q play "${choice[1]}"
    exit 0
  elif [[ "${choice[0]}" == 'f1' ]]; then
    filterAll
  elif [[ "${choice[0]}" == 'f2' ]]; then
    filterByArtist
  fi
}

has -v fzf mpc || die
isRunning mpd || die 'mpd not running'

declare filter='filterAll'
while true; do
  case "$1" in
    -A|--all)      filter='filterAll'        ; shift ;;
    -a|--artist)   filter='filterByArtist'   ; shift ;;
    -p|--playlist) filter='filterByPlaylist' ; shift ;;
    -h|--help)     usage                     ; exit  ;;
    *) break
  esac
done

mapfile -t songs < <("$filter")
(( ${#songs[@]} > 0 )) || die
printf '%s\n' "${songs[@]}" | mpc -q add
index=$(mpc playlist | wc -l)
if (( ${#songs[@]} > 1 )); then
  index=$(( index - ${#songs[@]} + 1))
fi
mpc -q play "$index"
