#!/usr/bin/env bash

preview='bat --color=always --style=header,numbers -H {2} {1}'

command='rg --color=always -n'

fzf -d: \
--ansi \
--query="$1" \
--phony \
--bind="change:reload:$command {q}" \
--bind="start:reload:$command {q}" \
--bind='enter:execute:$EDITOR {1}' \
--preview-window='+{2}-/2' \
--preview="[[ -n {1} ]] && $preview"
