#!/usr/bin/env bash

preview='bat --color=always --style=header,numbers -H {2} {1}'

rg --color=always -n "$1" 2> /dev/null |
fzf -d: \
--ansi \
--query="$1" \
--phony \
--bind="change:reload:rg --color=always -n {q}" \
--bind='enter:execute:v {1}' \
--preview-window='+{2}-/2' \
--preview="[[ -n {1} ]] && $preview"
